export const ROUTES = {
  login: '/login',
  authCallback: '/auth/callback',
  setup: '/setup',
  home: '/',
  dashboard: '/dashboard',
  settings: '/settings',
  categories: '/categories',
  budgetSettings: '/budget-settings',
  budgetSettingNew: '/budget-settings/new',
  budgetSettingEdit: (id: string) => `/budget-settings/${id}/edit`,
  transactions: '/transactions',
  transactionNew: '/transactions/new',
  transactionDetail: (id: string) => `/transactions/${id}`,
  splitBills: '/split-bill',
  splitBillNew: '/split-bill/new',
  splitBillManage: (id: string) => `/split-bill/${id}`,
  splitBillEdit: (id: string) => `/split-bill/${id}/edit`,
  splitBillPublic: (id: string) => `/bill/${id}`,
  tripDetail: (tripId: string) => `/split-bill/trips/${tripId}`,
  tripPublic: (tripId: string) => `/trip/${tripId}`,
} as const;
